---
- name: Clone node repo
  git:
    repo: '{{ aptos_repo }}'
    dest: '{{ aptos_directory }}'
    version: 'main'
    update: true
    force: true
    recursive: false

- name: Run/update Aptos prep script
  command: '{{ item }}'
  args:
    chdir: '{{ aptos_directory }}'
  with_items:
    - './scripts/dev_setup.sh -b'
  environment:
    PATH: '{{ path }}'

- name: Build CLI binary
  command: '{{ item }}'
  args:
    chdir: '{{ aptos_directory }}'
  with_items:
    - 'nice -n 10 cargo build --package aptos --release'
  environment:
    PATH: '{{ path }}'

- name: Clone node repo
  git:
    repo: '{{ aptos_repo }}'
    dest: '{{ aptos_directory }}'
    version: '{{ aptos_version }}'
    update: true
    force: true
    recursive: false

- name: Build node binary
  command: '{{ item }}'
  args:
    chdir: '{{ aptos_directory }}'
  with_items:
    - 'nice -n 10 cargo build --package aptos-node --release'
  environment:
    PATH: '{{ path }}'

- name: Copy binaries
  become: true
  copy:
    src: '{{ aptos_directory }}/target/release/{{ item }}'
    dest: '/usr/local/bin'
    owner: root
    group: root
    mode: 0755
    remote_src: true
  loop:
    - aptos
    - aptos-node
